spring.application.name=actuator-practice
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.server.port=9001
info.app.name=My actuator practice
info.app.version=1.0.0
info.app.author=Matija

spring.security.user.name=admin
spring.security.user.password=admin123